/**
 * Generated by Serve Engine
 *
 * @author gitesh
 */
package ${service.group.toLowerCase()};

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.module.jsonSchema.JsonSchemaGenerator;
import org.modelmapper.ModelMapper;
import org.modelmapper.jackson.JsonNodeValueReader;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class ApplicationConfiguration {

	@Bean
	public JsonSchemaGenerator schemaGenerator() {
		return new JsonSchemaGenerator(new ObjectMapper());
	}

	@Bean
	public ModelMapper modelMapperInstance() {
		ModelMapper modelMapper = new ModelMapper();
		modelMapper.getConfiguration().addValueReader(new JsonNodeValueReader());
		configTypeMaps(modelMapper);
		return modelMapper;
	}

	/**
	 * This method is used to configure type maps for mapper.
	 *
	 * @param mapper
	 */
	private void configTypeMaps(ModelMapper mapper) {
		// TODO: Configure type maps over here if needed
		// Its a good idea to skip id field of a model if its being genrated by the system automatically
		// One also needs to skip resource fields which create a cyclic redundancy
	}
}
