---
server:
  port: 8080

zuul:
  sensitive-headers:
  - Cookie
  - Set-Cookie
  prefix: /api
  routes:
    products: 
      path: /products/**
      serviceId: product-service

eureka:
  client:
    registerWithEureka: false
    enabled: true
    service-url:
      defaultZone: http://discovery:8761/eureka/,http://localhost:8761/eureka/

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG