---
spring:
  profiles: dev
  
server:
  port: 8080

zuul:
  sensitive-headers:
  - Cookie
  - Set-Cookie
  prefix: /api
  routes:
    products: 
      path: /products/**
      serviceId: product-service

eureka:
  client:
    registerWithEureka: false
    enabled: true

---
spring:
  profiles: local
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  
logging:
  level:
    ROOT: debug
    
---
spring:
  profiles: docker
  
eureka:
  instance:
    hostname: edge
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
  
logging:
  level:
    ROOT: error
    