/**
 * Generated by Serve Engine
 * @author gitesh
 */
package ${service.group.toLowerCase()}.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.repository.NoRepositoryBean;

/**
 * @param <T>
 * 		- Generated Model Class
 * @param <ID>
 * 		- Identifier Type
 */
@NoRepositoryBean
public interface BaseServeRepository<T, ID> extends JpaRepository<T, ID>, JpaSpecificationExecutor<T> {

}
