/**
 * Generated by Serve Engine
 *
 * @author gitesh
 */
package com.giteshdalal.emailservice.exception;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

@ResponseStatus(HttpStatus.BAD_REQUEST)
public class BadRequestEmailServiceException extends RuntimeException {

	private static final long serialVersionUID = 400L;

	public BadRequestEmailServiceException() {
	}

	public BadRequestEmailServiceException(String message) {
		super(message);
	}

	public BadRequestEmailServiceException(String message, Throwable cause) {
		super(message, cause);
	}

	public BadRequestEmailServiceException(Throwable cause) {
		super(cause);
	}
}
