/**
 * Generated by Serve Engine
 *
 * @author gitesh
 */
package com.giteshdalal.emailservice.exception;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

@ResponseStatus(HttpStatus.FORBIDDEN)
public class ForbiddenEmailServiceException extends RuntimeException {

	private static final long serialVersionUID = 403L;

	public ForbiddenEmailServiceException() {
	}

	public ForbiddenEmailServiceException(String message) {
		super(message);
	}

	public ForbiddenEmailServiceException(String message, Throwable cause) {
		super(message, cause);
	}

	public ForbiddenEmailServiceException(Throwable cause) {
		super(cause);
	}
}
