/**
 * Generated by Serve Engine
 *
 * @author gitesh
 */
package com.giteshdalal.emailservice.exception;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

@ResponseStatus(HttpStatus.GATEWAY_TIMEOUT)
public class GatewayTimeoutEmailServiceException extends RuntimeException {

	private static final long serialVersionUID = 504L;

	public GatewayTimeoutEmailServiceException() {
	}

	public GatewayTimeoutEmailServiceException(String message) {
		super(message);
	}

	public GatewayTimeoutEmailServiceException(String message, Throwable cause) {
		super(message, cause);
	}

	public GatewayTimeoutEmailServiceException(Throwable cause) {
		super(cause);
	}
}
