/**
 * Generated by Serve Engine
 *
 * @author gitesh
 */
package com.giteshdalal.emailservice.exception;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
public class InternalErrorEmailServiceException extends RuntimeException {

	private static final long serialVersionUID = 500L;

	public InternalErrorEmailServiceException() {
	}

	public InternalErrorEmailServiceException(String message) {
		super(message);
	}

	public InternalErrorEmailServiceException(String message, Throwable cause) {
		super(message, cause);
	}

	public InternalErrorEmailServiceException(Throwable cause) {
		super(cause);
	}
}
