/**
 * Generated by Serve Engine
 *
 * @author gitesh
 */
package com.giteshdalal.emailservice.exception;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

@ResponseStatus(HttpStatus.NOT_IMPLEMENTED)
public class NotImplementedEmailServiceException extends RuntimeException {

	private static final long serialVersionUID = 501L;

	public NotImplementedEmailServiceException() {
	}

	public NotImplementedEmailServiceException(String message) {
		super(message);
	}

	public NotImplementedEmailServiceException(String message, Throwable cause) {
		super(message, cause);
	}

	public NotImplementedEmailServiceException(Throwable cause) {
		super(cause);
	}
}
