/**
 * Generated by Serve Engine
 *
 * @author gitesh
 */
package com.giteshdalal.emailservice.exception;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

@ResponseStatus(HttpStatus.PAYMENT_REQUIRED)
public class PaymentRequiredEmailServiceException extends RuntimeException {

	private static final long serialVersionUID = 402L;

	public PaymentRequiredEmailServiceException() {
	}

	public PaymentRequiredEmailServiceException(String message) {
		super(message);
	}

	public PaymentRequiredEmailServiceException(String message, Throwable cause) {
		super(message, cause);
	}

	public PaymentRequiredEmailServiceException(Throwable cause) {
		super(cause);
	}
}
