/**
 * Generated by Serve Engine
 *
 * @author gitesh
 */
package com.giteshdalal.emailservice.exception;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

@ResponseStatus(HttpStatus.REQUEST_TIMEOUT)
public class RequestTimeoutEmailServiceException extends RuntimeException {

	private static final long serialVersionUID = 408L;

	public RequestTimeoutEmailServiceException() {
	}

	public RequestTimeoutEmailServiceException(String message) {
		super(message);
	}

	public RequestTimeoutEmailServiceException(String message, Throwable cause) {
		super(message, cause);
	}

	public RequestTimeoutEmailServiceException(Throwable cause) {
		super(cause);
	}
}
