/**
 * Generated by Serve Engine
 *
 * @author gitesh
 */
package com.giteshdalal.emailservice.exception;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

@ResponseStatus(HttpStatus.TOO_MANY_REQUESTS)
public class TooManyRequestsEmailServiceException extends RuntimeException {

	private static final long serialVersionUID = 429L;

	public TooManyRequestsEmailServiceException() {
	}

	public TooManyRequestsEmailServiceException(String message) {
		super(message);
	}

	public TooManyRequestsEmailServiceException(String message, Throwable cause) {
		super(message, cause);
	}

	public TooManyRequestsEmailServiceException(Throwable cause) {
		super(cause);
	}
}
