/**
 * Generated by Serve Engine
 *
 * @author gitesh
 */
package com.giteshdalal.emailservice.exception;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

@ResponseStatus(HttpStatus.SERVICE_UNAVAILABLE)
public class UnavailableEmailServiceException extends RuntimeException {

	private static final long serialVersionUID = 503L;

	public UnavailableEmailServiceException() {
	}

	public UnavailableEmailServiceException(String message) {
		super(message);
	}

	public UnavailableEmailServiceException(String message, Throwable cause) {
		super(message, cause);
	}

	public UnavailableEmailServiceException(Throwable cause) {
		super(cause);
	}
}
