---
spring:
  profiles: dev

eureka:
  client: # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    
---
spring:
  profiles: local
    
logging:
  level:
    org.springframework.cloud.netflix: debug
    
---
spring:
  profiles: docker
  
eureka:
  instance:
    hostname: discovery
    
logging:
  level:
    ROOT: error
    