version: '3.5'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: serve
      MYSQL_USER: serve
      MYSQL_PASSWORD: serve_password
      MYSQL_ROOT_PASSWORD: root_password
    container_name: serve_container_db
    restart: on-failure
    ports:
    - "3300:3306"
  discovery:
    image: serve_discovery
    build: 
      context: .
      dockerfile: ./discoveryservice/Dockerfile
    container_name: serve_container_discovery
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
    ports:
    - "8761:8761"
  config:
    image: serve_config
    build: 
      context: .
      dockerfile: ./configservice/Dockerfile
    container_name: serve_container_config
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
    depends_on:
      - discovery
    ports:
    - "8088:8088"
  edge:
    image: serve_edge
    build: 
      context: .
      dockerfile: ./edgeservice/Dockerfile
    container_name: serve_container_edge
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
    depends_on:
      - config
    ports:
    - "8080:8080"
  auth:
    image: serve_auth
    build: 
      context: .
      dockerfile: ./authservice/Dockerfile
    container_name: serve_container_auth
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
    depends_on:
      - config
      - db
    ports:
    - "8090:8090"
  product:
    image: serve_product
    build: 
      context: .
      dockerfile: ./productservice/Dockerfile
    container_name: serve_container_product
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
    depends_on:
      - auth
    ports:
    - "8091:8091"
