version: '3.5'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: serve
      MYSQL_USER: serve
      MYSQL_PASSWORD: serve_password
      MYSQL_ROOT_PASSWORD: root_password
    container_name: serve_container_db
    restart: on-failure
    ports:
      - "3300:3306"
  vault:
    image: vault
    container_name: serve_container_vault
    cap_add:
      - IPC_LOCK
    environment:
      # This token will be used by vault to authenticate requests
      VAULT_DEV_ROOT_TOKEN_ID: 47d1d790-0cce-384f-5a28-3cf2eb9e5489
    ports:
      - "8200:8200"
  vault-init:
    image: vault
    volumes:
      - './vault:/config'
      - './wait-for:/wait-for'
    container_name: serve_container_vault_init
    environment:
      VAULT_DEV_TOKEN: 47d1d790-0cce-384f-5a28-3cf2eb9e5489 # This token will be used by vault to authenticate on VAULT_ADDR
      VAULT_ADDR: 'http://vault:8200' # This will be used to connect to vault server
      CONFIG_DIR: '/config' # Used inside init.sh to locate data files
    command:
      - 'sh'
      - '-c'
      - '/wait-for vault:8200 -t 4 && /config/init.sh'
    restart: on-failure
    depends_on:
      - vault
  auth:
    image: jboss/keycloak:6.0.1
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - './keycloak/config:/config'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=nimda
      - DB_VENDOR=mysql
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_ADDR=db
      - DB_PORT=3306
      - DB_DATABASE=serve
    ports:
      - "8090:8090"
    depends_on:
      - db
  discovery:
    image: serve_discovery
    build:
      context: .
      dockerfile: ./discoveryservice/Dockerfile
    container_name: serve_container_discovery
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
    ports:
      - "8761:8761"
  edge:
    image: serve_edge
    build:
      context: .
      dockerfile: ./edgeservice/Dockerfile
    container_name: serve_container_edge
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
    depends_on:
      - config
      - vault
    ports:
      - "8080:8080"
  email:
    image: serve_email
    build:
      context: .
      dockerfile: ./emailservice/Dockerfile
    container_name: serve_container_email
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
    depends_on:
      - auth
    ports:
      - "8084:8084"
  config:
    image: serve_config
    build:
      context: .
      dockerfile: ./configservice/Dockerfile
    container_name: serve_container_config
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
    depends_on:
      - discovery
    ports:
      - "8088:8088"
