version: '3'
services:
  discovery:
    image: serve_discovery
    build: 
      context: ./discoveryservice
      shm_size: '256M'
    container_name: serve_container_discovery
    ports:
    - "8761:8761"
  config:
    image: serve_config
    build: 
      context: ./configservice
      shm_size: '256M'
    container_name: serve_container_config
    depends_on:
      - discovery
    ports:
    - "8088:8088"
  auth:
    image: serve_auth
    build: 
      context: ./authservice
      shm_size: '256M'
    container_name: serve_container_auth
    depends_on:
      - config
    ports:
    - "8090:8090"
  product:
    image: serve_product
    build: 
      context: ./productservice
      shm_size: '256M'
    container_name: serve_container_product
    depends_on:
      - config
    ports:
    - "8091:8091"
  edge:
    image: serve_edge
    build: 
      context: ./edgeservice
      shm_size: '256M'
    container_name: serve_container_edge
    depends_on:
      - product
      - auth
    ports:
    - "8080:8080"
