version: '3'
services:
  discovery:
    image: serve_discovery
    build: 
      context: ./discoveryservice
      shm_size: '512M'
    container_name: serve_container_discovery
    ports:
    - "8761:8761"
  config:
    image: serve_config
    build: 
      context: ./configservice
      shm_size: '512M'
    container_name: serve_container_config
    depends_on:
      - discovery
    ports:
    - "8888:8888"
  product:
    image: serve_product
    build: 
      context: ./productservice
      shm_size: '512M'
    container_name: serve_container_product
    depends_on:
      - config
    ports:
    - "8080:8080"
