/**
 * Generated by Serve Engine
 *
 * @author gitesh
 */
package com.giteshdalal.userservice.proxy;

import java.util.Locale;

import org.springframework.data.domain.Pageable;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

/**
 * @param <ID>
 * 		- Identifier Type Class
 */
public interface ServeServiceProxy<ID> {

	@RequestMapping(value = "/{uid}", method = RequestMethod.GET)
	ResponseEntity getById(@PathVariable("uid") ID uid, @RequestParam("locale") Locale locale);

	@RequestMapping(method = RequestMethod.GET)
	ResponseEntity getAll(Pageable pageable, @RequestParam(value = "q", required = false) String query,
			@RequestParam("locale") Locale locale);

	@RequestMapping(method = RequestMethod.POST, consumes = { MediaType.APPLICATION_JSON_VALUE })
	ResponseEntity add(@RequestBody Object resource, @RequestParam("locale") Locale locale);

	@RequestMapping(value = "/{uid}", method = RequestMethod.PUT, consumes = { MediaType.APPLICATION_JSON_VALUE })
	ResponseEntity overwrite(@RequestBody Object resource, @RequestParam("locale") Locale locale);

	@RequestMapping(value = "/{uid}", method = RequestMethod.DELETE)
	ResponseEntity delete(@PathVariable("uid") ID uid, @RequestParam("locale") Locale locale);
}
