/**
 * Generated by Serve Engine
 *
 * @author gitesh
 */
package com.giteshdalal.userservice;

import feign.Logger;
import feign.Request;
import feign.RequestInterceptor;
import org.springframework.cloud.security.oauth2.client.feign.OAuth2FeignRequestInterceptor;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.oauth2.client.OAuth2ClientContext;
import org.springframework.security.oauth2.client.resource.OAuth2ProtectedResourceDetails;

@Configuration
public class ServeFeignConfiguration {

	@Bean
	public RequestInterceptor requestInterceptor(OAuth2ClientContext context, OAuth2ProtectedResourceDetails resourceDetails) {
		return new OAuth2FeignRequestInterceptor(context, resourceDetails);
	}

	@Bean
	Logger.Level feignLoggerLevel() {
		return Logger.Level.BASIC;
	}

	@Bean
	Request.Options timeoutOptions() {
		return new Request.Options();
	}
}
