---
server:
  port: 8091
  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/,http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://db:3300/serve?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      
logging:
  level:
    org.springframework.security: debug
    com.giteshdalal.productservice: info
