---
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8090
      
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
   
security:
  oauth2:
    resource-ids: ProductService,Oauth2Service
    validity:
      access-token: 10000
      refresh-token: 30000
    keystore:
      key: serve_key
      file: keystore.jks
      password: password
      
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/serve?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: infrrd@123
 
logging:
  level:
    ROOT: debug
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://db:3306/serve?useSSL=false
    username: root
    password: root_password

logging:
  level:
    ROOT: error

eureka:
  instance:
    hostname: auth
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
