/**
 * Generated by Serve Engine
 * @author gitesh
 */
package com.giteshdalal.userservice.service;

import java.util.List;
import java.util.Locale;
import java.util.Optional;

import com.fasterxml.jackson.databind.JsonNode;
import com.giteshdalal.userservice.query.SearchCriteria;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * @param <RT>
 * 		- Generated Resource Type
 * @param <ID>
 * 		- Identifier Type
 */
public interface BaseServeService<RT, ID> {

	Optional<RT> findByUid(ID uid, Locale locale);

	Page<RT> findAll(List<SearchCriteria> params, Pageable pageable, Locale locale);

	RT save(RT resource, Locale locale);

	RT update(ID uid, RT resource, Locale locale);

	void patch(ID uid, JsonNode updates, Locale locale);

	void deleteByUid(ID uid, Locale locale);

}
