/**
 * Generated by Serve Engine
 *
 * @author gitesh
 */
package ${service.group.toLowerCase()}.exception;

import java.util.Locale;

import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

@FeignClient("email-service")
@RequestMapping("/email")
public interface EmailServiceProxy {

	@RequestMapping(value = "/{bean}", method = RequestMethod.POST, consumes = { MediaType.APPLICATION_JSON_VALUE })
	ResponseEntity triggerEmail(@PathVariable("bean") String beanId, @RequestBody Object resource,
			@RequestParam("locale") Locale locale);
}
