---
spring:
  profiles: dev
  
server:
  port: 8088
  
---
spring:
  profiles: local
 
logging:
  level:
    ROOT: debug
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
---
spring:
  profiles: docker

logging:
  level:
    ROOT: error

eureka:
  instance:
    hostname: config
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
