/**
 * Generated by Serve Engine
 * @author gitesh
 */
package ${service.group.toLowerCase()}.query;

public enum SearchOperation {
	EQUALITY, NEGATION, GREATER_THAN, LESS_THAN, LIKE, STARTS_WITH, ENDS_WITH, CONTAINS;

	public static final String[] OPERATION_SET = { ":", "!", ">", "<", "~", "^", "$", "*" };

	public static SearchOperation getOperation(char input) {
		switch (input) {
		case ':':
			return EQUALITY;
		case '!':
			return NEGATION;
		case '>':
			return GREATER_THAN;
		case '<':
			return LESS_THAN;
		case '~':
			return LIKE;
		case '^':
			return STARTS_WITH;
		case '$':
			return ENDS_WITH;
		case '*':
			return CONTAINS;
		default:
			return EQUALITY;
		}
	}
}
