/**
 * Generated by Serve Engine
 * @author gitesh
 */
package ${service.group.toLowerCase()}.query;

import lombok.Data;

@Data
public class SearchCriteria {
	private String key;
	private SearchOperation operation;
	private Object value;
}
